### ISSUE TITLE
版本判断问题

### ISSUE THREAD

**Issue by fundon** [shm-open/code-push-cli#66]
发布了一个 `~1.0.0` 的热更新，为什么 `1.0.0` 的收取不到，`>1.0.0` 的版本确可以

**Comment by rocwind** [comment]
@fundon 
抱歉回复晚了.
`targetBinaryVersion` 的具体处理其实是在服务端的, 所以如果遇上问题的话, 可能需要看看code-push-server的逻辑.
服务端的逻辑主要在 https://github.com/shm-open/code-push-server/blob/master/src/core/utils/common.ts#L29, 会把具体的min/max version范围解析出来. 我尝试了一下, `~1.0.0` 会拆成 `min_version: 1000000000000000, max_version: 1000010000000000`, 看起来是正常的.
而我们最近的版本里修过这样一个问题有可能会有关: https://github.com/lisong/code-push-server/issues/173, 对应的fix: https://github.com/shm-open/code-push-server/pull/162, 已经发布过, 可以试试更新到最新版本看看.
如果问题依然存在, 希望能提供更多的一些信息方便复现/调试:
- 使用的server/cli版本
- 发布时的具体命令行

**Comment by fundon** [comment]
好的 我再尝试下

**Comment by 18706789739** [comment]
我的app版本号目前是10.1.7

发布10.1.1 - 10.1.999 可以接收到。
再发布 10.1.7 之后也可以接收到。

但在单独发布10.1.7之后，应用无法接受到10.1.1 - 10.1.999 范围发布的最新包

server 2.1.6  / cli 2.1.9

code-push release-react xxx android --t "10.1.1 - 10.1.999" --d Production --des "" -m true
code-push release-react xxx android --t "10.1.7" --d Production --des "" -m true
