### ISSUE TITLE
发布更新失败

### ISSUE THREAD

**Issue by zhonglikui** [shm-open/code-push-cli#99]
react native:0.72.1
错误如下：
`PS C:\work\AccountTemplate> code-push release-react test-android android -d Production -t 1.0.0                                                                                        
Running "react-native bundle" command:                                       

node node_modules\react-native\local-cli\cli.js bundle --assets-dest C:\Users\82636\AppData\Local\Temp\CodePush\CodePush --bundle-output C:\Users\82636\AppData\Local\Temp\CodePush\CodePush\index.android.bundle --dev false --entry-file index.js --platform android
Welcome to Metro v0.76.5
              Fast - Scalable - Integrated

info Writing bundle output to:, C:\Users\82636\AppData\Local\Temp\CodePush\CodePush\index.android.bundle
info Done writing bundle output
info Copying 31 asset files
info Done copying assets
[Error]  undefined is not iterable (cannot read property Symbol(Symbol.iterator))`

**Comment by khunghang16** [comment]
我也是

**Comment by liuzhenjie0311** [comment]
我遇到了类似的错误，不过我的错误是react-native更新到0.7以后启用了Hermes，这可能需要作者更新一下版本https://github.com/microsoft/react-native-code-push/issues/2036

**Comment by parz1** [comment]
RN0.72.4遇到一样的错误

**Comment by billxie1988** [comment]
这个问题我参考了新版本的RN迁移指南，hermesEnable 不一定会出现在android/app/build.gradle文件里 可能会出现在android/gradle.properties 里全局设置。之前的代码
`Array.from(buildGradle['project.ext.react']).includes('enableHermes: true');`
由于这个逻辑会报以上错误。 check the latest version 2.6.4
